/**
 * Regenerates supabase/seed.sql from src/data/seedCatalog.ts (single source of truth).
 * Run: npm run db:emit-seed
 */
import { writeFileSync } from 'fs';
import { join } from 'path';
import { SEED_LISTINGS, SEED_PROFILES } from '../src/data/seedCatalog';

function sqlStr(s: string): string {
  return `'${s.replace(/'/g, "''")}'`;
}

const root = process.cwd();
const handles = SEED_PROFILES.map((p) => p.handle).join(', ');

let out = `-- AUTO-GENERATED by npm run db:emit-seed — edit seedCatalog.ts instead.
-- Profiles (${SEED_PROFILES.length}): ${handles}
-- Listings: ${SEED_LISTINGS.length}
-- Run after supabase/schema.sql. Dev-only wipe of marketplace rows.

BEGIN;

DELETE FROM public.listings;
DELETE FROM public.profiles;

`;

for (const p of SEED_PROFILES) {
  out += `INSERT INTO public.profiles (id, handle, display_name, avatar_url, bio, campus, primary_meetup_spot, rating_avg, review_count, items_sold, followers_count, is_verified_edu) VALUES (${sqlStr(p.id)}, ${sqlStr(p.handle)}, ${sqlStr(p.displayName)}, ${sqlStr(p.avatarUrl)}, ${sqlStr(p.bio)}, ${sqlStr(p.campus)}, ${sqlStr(p.primaryMeetupSpot)}, ${p.ratingAvg}, ${p.reviewCount}, ${p.itemsSold}, ${p.followersCount}, ${p.isVerifiedEdu});\n`;
}

for (const l of SEED_LISTINGS) {
  const brandSql = l.brand == null ? 'NULL' : sqlStr(l.brand);
  const sizeSql = l.size == null ? 'NULL' : sqlStr(l.size);
  out += `INSERT INTO public.listings (id, seller_id, title, price, image_url, status, description, category, condition, brand, size, location_label) VALUES (${sqlStr(l.id)}, ${sqlStr(l.sellerId)}, ${sqlStr(l.title)}, ${sqlStr(l.price)}, ${sqlStr(l.imageUrl)}, ${sqlStr(l.status)}, ${sqlStr(l.description)}, ${sqlStr(l.category)}, ${sqlStr(l.condition)}, ${brandSql}, ${sizeSql}, ${sqlStr(l.locationLabel)});\n`;
}

out += `
ALTER TABLE public.listings ALTER COLUMN seller_id SET NOT NULL;
COMMIT;
`;

writeFileSync(join(root, 'supabase/seed.sql'), out);
console.log(`Wrote supabase/seed.sql (${SEED_PROFILES.length} profiles, ${SEED_LISTINGS.length} listings).`);
